import os
import uuid
import asyncio
from pathlib import Path
from fastapi import APIRouter, UploadFile, File, HTTPException, Depends, BackgroundTasks
from sqlalchemy.ext.asyncio import AsyncSession
from backend.db.database import get_db, AsyncSessionLocal
from backend.db import crud, models, jobs
from backend.agents.state import FileArtifact
from backend.agents.graph import workflow_app
from backend.agents.data_explorer import DataExplorerAgent
from backend.agents.follow_up import FollowUpAgent
from backend.core.utils import get_dataframe_metadata
from backend.config import settings

router = APIRouter()

# Setup Upload Directory
BASE_DIR = Path(__file__).resolve().parent.parent
UPLOAD_DIR = BASE_DIR / "uploads"
os.makedirs(UPLOAD_DIR, exist_ok=True)

async def run_workflow_background(session_id: str, job_id: str, file_path: str, file_name: str, user_request: str):
    async with AsyncSessionLocal() as db:
        try:
            # 1. Update job status to 'running'
            await jobs.update_job_status(db, job_id, "running")
            await db.commit()
            
            # 2. Build initial state
            input_artifact = FileArtifact(
                artifact_id=f"file_{session_id}",
                name=file_name,
                path=Path(file_path),
                source="upload"
            )
            
            initial_state = {
                "session_id": session_id,
                "user_request": user_request,
                "workflow_status": "idle",
                "input_files": [input_artifact],
                "output_files": [],
                "agent_queue": [],
                "agent_results": {},
                "shared_data": {},
                "workbook_insights": [],
                "errors": [],
                "messages": []
            }
            
            # 3. Invoke LangGraph workflow
            final_state = await workflow_app.ainvoke(initial_state)
            
            # Save assistant messages generated by graph to DB
            for msg in final_state.get("messages", []):
                if msg["role"] == "assistant":
                    await crud.create_message(
                        db,
                        session_id,
                        role="assistant",
                        content=msg["content"]
                    )
            
            errors = final_state.get("errors", [])
            if errors:
                await jobs.update_job_status(db, job_id, "failed", errors=errors)
            else:
                output_files = []
                for artifact in final_state.get("output_files", []):
                    # We expose the file name relative to settings.EXPORT_DIR or downloads
                    output_files.append({
                        "name": artifact.name,
                        "path": str(artifact.path)
                    })
                    
                result_payload = {
                    "final_summary": final_state.get("final_summary", ""),
                    "output_files": output_files
                }
                await jobs.update_job_status(db, job_id, "completed", result=result_payload)
                
            await db.commit()
        except asyncio.CancelledError:
            # Task was cancelled
            pass
        except Exception as e:
            await jobs.update_job_status(db, job_id, "failed", errors=[str(e)])
            await db.commit()
        finally:
            jobs.active_tasks.pop(job_id, None)

@router.post("/upload")
async def upload_file(
    file: UploadFile = File(...),
    db: AsyncSession = Depends(get_db)
):
    ext = file.filename.split(".")[-1].lower()
    if ext not in settings.get_allowed_extensions_list():
        raise HTTPException(status_code=400, detail="Unsupported file type.")
    
    session_id = str(uuid.uuid4())
    file_path = UPLOAD_DIR / f"{session_id}.{ext}"
    
    # Save file to disk
    with open(file_path, "wb") as f:
        content = await file.read()
        f.write(content)
        
    import shutil
    os.makedirs(settings.EXPORT_DIR, exist_ok=True)
    report_filename = f"{session_id}_report.xlsx"
    report_path = Path(settings.EXPORT_DIR) / report_filename
    if ext in ["xlsx", "xls"]:
        shutil.copy(file_path, report_path)
    else:
        # If it's a CSV, convert it to Excel so openpyxl can append sheets later
        import pandas as pd
        df = pd.read_csv(file_path)
        df.to_excel(report_path, index=False)
        
    db_session = await crud.create_session(db, file.filename, str(file_path), session_id=session_id)
    await crud.update_session_report_path(db, session_id, str(report_path))
    
    # Try profiling to extract initial metadata
    try:
        import pandas as pd
        if ext == "csv":
            df = pd.read_csv(file_path)
        else:
            df = pd.read_excel(file_path)
        metadata = get_dataframe_metadata(df)
    except Exception as e:
        metadata = {"error": f"Failed to extract metadata: {e}"}
        
    await crud.create_message(
        db,
        session_id,
        "assistant",
        f"Uploaded {file.filename}. Ready for analysis!",
        metadata={"df_metadata": metadata}
    )
    await db.commit()
    
    return {
        "session_id": session_id,
        "file_name": file.filename,
        "metadata": metadata
    }

@router.post("/analyze/async")
async def start_analysis(
    session_id: str,
    user_request: str,
    db: AsyncSession = Depends(get_db)
):
    session = await crud.get_session(db, session_id)
    if not session:
        raise HTTPException(status_code=404, detail="Session not found")
        
    job_id = str(uuid.uuid4())
    
    # Save user message to chat history
    await crud.create_message(db, session_id, "user", user_request)
    
    # Create database job tracking record
    await jobs.create_job(db, session_id, job_id, user_request)
    await db.commit()
    
    # Spawn background task
    task = asyncio.create_task(
        run_workflow_background(
            session_id=session_id,
            job_id=job_id,
            file_path=session.file_path,
            file_name=session.file_name,
            user_request=user_request
        )
    )
    jobs.active_tasks[job_id] = task
    
    return {
        "job_id": job_id,
        "status": "pending"
    }

@router.get("/analyze/status/{job_id}")
async def get_analysis_status(
    job_id: str,
    db: AsyncSession = Depends(get_db)
):
    job = await jobs.get_job(db, job_id)
    if not job:
        raise HTTPException(status_code=404, detail="Job not found")
        
    return {
        "job_id": job.id,
        "status": job.status,
        "result": job.result,
        "errors": job.errors
    }

@router.post("/analyze/cancel/{job_id}")
async def cancel_analysis(
    job_id: str,
    db: AsyncSession = Depends(get_db)
):
    job = await jobs.get_job(db, job_id)
    if not job:
        raise HTTPException(status_code=404, detail="Job not found")
        
    cancelled_job = await jobs.cancel_job(db, job_id)
    await db.commit()
    
    return {
        "job_id": job_id,
        "status": cancelled_job.status if cancelled_job else "cancelled"
    }

@router.post("/chat/{session_id}")
async def chat(
    session_id: str,
    message: str,
    db: AsyncSession = Depends(get_db)
):
    session = await crud.get_session(db, session_id)
    if not session:
        raise HTTPException(status_code=404, detail="Session not found")
        
    # Get history
    history_models = await crud.get_messages(db, session_id)
    history = [{"role": m.role, "content": m.content} for m in history_models]
    
    # Save user message to database
    await crud.create_message(db, session_id, "user", message)
    history.append({"role": "user", "content": message})
    await db.commit()
    
    # Profile workbook
    input_artifact = FileArtifact(
        artifact_id=f"file_{session_id}",
        name=session.file_name,
        path=Path(session.file_path),
        source="upload"
    )
    
    temp_state = {
        "session_id": session_id,
        "report_path": getattr(session, "report_path", None),
        "input_files": [input_artifact],
        "messages": history,
        "follow_up_request": message,
        "errors": []
    }
    
    explorer = DataExplorerAgent()
    temp_state = explorer.process(temp_state)
    
    # Process with FollowUp Agent
    follow_up = FollowUpAgent()
    final_state = follow_up.process(temp_state)
    
    result = final_state.get("follow_up_result")
    
    response_content = "Failed to compile follow-up response."
    metadata = {}
    if result:
        response_content = result.summary
        metadata = {
            "result_kind": result.result_kind,
            "result_value": result.result_value,
            "generated_code": result.generated_code,
            "error": result.error,
            "fig_base64": result.fig_base64
        }
        
    await crud.create_message(
        db,
        session_id,
        "assistant",
        response_content,
        msg_type="code" if (result and result.generated_code) else "text",
        metadata=metadata
    )
    await db.commit()
    
    return {
        "role": "assistant",
        "content": response_content,
        "msg_type": "code" if (result and result.generated_code) else "text",
        "metadata": metadata
    }

@router.get("/sessions/{session_id}/messages")
async def get_messages(session_id: str, db: AsyncSession = Depends(get_db)):
    messages = await crud.get_messages(db, session_id)
    return [
        {
            "id": m.id,
            "session_id": m.session_id,
            "role": m.role,
            "content": m.content,
            "msg_type": m.msg_type,
            "metadata": m.metadata_json,
            "created_at": m.created_at
        } for m in messages
    ]

from fastapi.responses import FileResponse

@router.get("/export/{session_id}")
async def export_report(session_id: str, db: AsyncSession = Depends(get_db)):
    session = await crud.get_session(db, session_id)
    if not session or not getattr(session, "report_path", None) or not os.path.exists(session.report_path):
        raise HTTPException(status_code=404, detail="Export report not found")
        
    return FileResponse(
        path=session.report_path,
        media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        filename=f"exodus_report_{session_id}.xlsx"
    )
